### ISSUE TITLE
Please add support for AtMega2560

### ISSUE THREAD

**Issue by RoberMC** [MCUdude/MiniCore#101]
This is a feature request, not an issue, but here it is ;)

Sometimes i need a greater amount of i/o pins, and i wish i could use this magnificent MiniCore with the Atmega2560.

Thanks!

**Comment by MCUdude** [comment]
Well, you have [MegaCore](https://github.com/MCUdude/MegaCore) for that 🙂
Practically identical to MiniCore, but with support for the most popular 64 and 100 pin AVRs.

The Arduino Mega has only 70 IO pins broken out and mapped to Arduino pin, even though the ATmega2560 has 86 IO pins. If you use MegaCore you can use all 86 as long as you have physical access to them.
