### ISSUE TITLE
Burning bootloader on ATMEGA8 could not find any USB device

### ISSUE THREAD

**Issue by wilson584** [MCUdude/MiniCore#102]
I plugged in my Atmega8A into my arduino uno board. When I tried to burn the bootloader, I encountered the error 

> avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\Wilson\AppData\Local\Arduino15\packages\MiniCore\hardware\avr\2.0.3/avrdude.conf"

         Using Port                    : usb
         Using Programmer              : stk500v2
avrdude: usbdev_open(): did not find any USB device "usb" (0x03eb:0x2104)

avrdude done.  Thank you.

Error while burning bootloader.

![image](https://user-images.githubusercontent.com/22119363/61587059-3a3ae500-ab37-11e9-8478-317545a46e19.png)

**Comment by MCUdude** [comment]
You can't just burn the bootloader to an ATmega8 without using a dedicated programmer. Do you have an AVRISP mkii?

**Comment by MCUdude** [comment]
You will have to use a dedicated programmer for this. There's plenty of tutorials around on how to do this.
