### ISSUE TITLE
PB series not working even with Arduino AVR boards installed

### ISSUE THREAD

**Issue by JasXSL** [MCUdude/MiniCore#112]
Settings:
* Board: ATmega8
* Clock: 16mhz external
* BOD 2.7V
* LTO Disabled
* Bootloader: Yes (UART0)
* Arduino AVR boards package is installed (1.8.1)
* Arduino 1.8.10

The value of PB0 seems to be 0 (should be 8 for ATmega8). The Arduino AVR boards package is installed and up to date.

**Comment by MCUdude** [comment]
PB0 is defined as 0 in the file `iom8.h`. It's supposed to be that way.

It's just a macro to make code more readable. If you want to set PB0 high, you'll just write it this way: `PORTB |= (1 << PB0);`

**Comment by JasXSL** [comment]
Huh guess they are. I'm used to using them to refer to pins directly on ATtiny and ESP MCUs.
