### ISSUE TITLE
Back fuses was unreliable

### ISSUE THREAD

**Issue by Samuel-ZDM** [MCUdude/MiniCore#113]
Hello!
First I configured my arduino nano with bootloader. The settings used were:
board: ATmega328
Clock: 1MHz internal
BOD: 1.8v
Compiler LTO: disabled
Variant: 328P
Bootloader: Yes UART0

PlatformIO was used.
I put this bootloader on arduino uno. The following errors appear after uploading DHT22 code:

avrdude: 7212 bytes of flash written
avrdude: verifying flash memory against .pio\build\MiniCore\firmware.hex:
avrdude: load data flash data from input file .pio\build\MiniCore\firmware.hex:
avrdude: input file .pio\build\MiniCore\firmware.hex contains 7212 bytes
avrdude: reading on-chip flash data:

Reading | #####################
avrdude: stk500_paged_load(): (a) protocol error, expect=0x10, resp=0x44
avrdude: stk500_cmd(): programmer is out of sync
avr_read(): error reading address 0x0000
    read operation not supported for memory "flash"
avrdude: failed to read all of flash memory, rc=-2

avrdude: stk500_cmd(): programmer is out of sync
avrdude: stk500_cmd(): programmer is out of sync
avrdude: stk500_cmd(): programmer is out of sync
avrdude: stk500_cmd(): programmer is out of sync
avrdude: safemode: Sorry, reading back fuses was unreliable. I have given up and exited programming mode
avrdude: stk500_disable(): protocol error, expect=0x14, resp=0x74

**Comment by MCUdude** [comment]
The internal oscillator is not necessary very accurate and may cause issues when uploading using bootloader. Try using the external crystal instead and divide down the clock speed by utilizing the CLKPR register, or upload using an ISP programmer
