### ISSUE TITLE
Non-standard function naming in README

### ISSUE THREAD

**Issue by finnbear** [MCUdude/MiniCore#120]
I saw this in the main README file:
```
portMode()
portRead()
portWrite()
```
When I looked at your code, you seemed to be using the standard
```
pinMode()
digitalRead()
digitalWrite()
```
Is this a typo in the README or something bigger?

**Comment by MCUdude** [comment]
If you read the whole section, you can see that this is some functionality ported from the [Wiring project](http://wiring.org.co), which Arduino is based on.

[You should also read this](https://github.com/MCUdude/MiniCore/blob/master/Wiring_reference.md)
