### ISSUE TITLE
Use PB6 and PB7 in PlatformIO?

### ISSUE THREAD

**Issue by nullstalgia** [MCUdude/MiniCore#127]
Title kinda says it all. I'd like to use PlatformIO due to it being a nicer IDE than the typical Arduino one, but I'm also forced to use PB6 and PB7 as IO pins due to me adapting a new sketch to an older PCB made for a specific program.

**Comment by MCUdude** [comment]
That's not a problem at all. Just burn the bootloader for the 1 og 8 MHz internal oscillator, and you're good to go. You can do this in Platformio too.

**Comment by nullstalgia** [comment]
Oh? I'm just stuck wondering how you'd declare the pins. Is it also 20 and 21?

**Comment by MCUdude** [comment]
They are already defined. Look at the pinout diagrams in the Readme file.
