### ISSUE TITLE
disablePower() and ATmega328PB

### ISSUE THREAD

**Issue by LaZsolt** [MCUdude/MiniCore#128]
ATmega328PB has doubled SPI, UART, Wire interfaces, more timers than 328P and Peripherial Touch Controller.
Has any effects enablePower() and disablePower() functions on this interfaces?

**Comment by MCUdude** [comment]
I don't think so. IIRC avr/power.h is not updated with the new features that the 328PB has. There's nothing I can do about it either. You'll have to contact the Arduino devs for this, or use the registers to turn these peripherals on or off.
