### ISSUE TITLE
Fuses not set when not using bootloader

### ISSUE THREAD

**Issue by Evidlo** [MCUdude/MiniCore#134]
I'm trying to use MiniCore on an atmega328p with the internal 8MHz oscillator.  

However, when I have these options set, I noticed my program is running 8x too slow:

![Menu_711](https://user-images.githubusercontent.com/5455841/78837425-a9a07f80-79b9-11ea-9ad3-de37a2204abe.png)

I can manually run avrdude to set the low fuse to `0xe2` to fix this.

Would it make sense to still set the [low fuse](https://github.com/MCUdude/MiniCore/blob/master/avr/boards.txt#L167) regardless of whether a bootloader is being used?

**Comment by MCUdude** [comment]
Fuses aren't set when you just upload. Ironically, you will have to run **Burn Bootloader** in order to set the fuses.
