### ISSUE TITLE
duplicate analogInPinToBit definition

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MiniCore#135]
At line 180, and again at 201.  This was not from a live test but from reviewing the pin macros.
https://github.com/MCUdude/MiniCore/blob/master/avr/cores/MCUdude_corefiles/Arduino.h#L201

This is a good example of why it is better to use inline functions rather than macros.  With an inline function you'd get a multiple definition error.

**Comment by MCUdude** [comment]
Thanks for reporting!
