### ISSUE TITLE
avrdude: usbdev_open(): did not find any USB device "usb" (0x03eb:0x2104)

### ISSUE THREAD

**Issue by lwh456789** [MCUdude/MiniCore#136]
I'm using Mega 2560, so I can compile and upload successfully, but I can't burn it, so what's the problem
![捕获1](https://user-images.githubusercontent.com/63505637/79754959-e28e0c00-834a-11ea-8c9d-e0efb52cdd8b.PNG)
![捕获2](https://user-images.githubusercontent.com/63505637/79754972-ea4db080-834a-11ea-81ee-60517a639aa6.PNG)
![捕获3](https://user-images.githubusercontent.com/63505637/79754991-f0dc2800-834a-11ea-884e-e3df505db4cd.PNG)

**Comment by MCUdude** [comment]
You will need a dedicated programmer if you want to burn the bootloader. The first screenshots show us that Avrdude can't find the programmer you've selected, which is the AVRISPmkII. Do you have an AVRISPmkII?

**Comment by lwh456789** [comment]
It was AVRISP MKII
![IMG_8325](https://user-images.githubusercontent.com/63505637/79755693-1b7ab080-834c-11ea-8582-0e2e37f55737.PNG)

**Comment by lwh456789** [comment]
![捕获4](https://user-images.githubusercontent.com/63505637/79756061-a196f700-834c-11ea-81a6-efd6c70061a1.PNG)

**Comment by MCUdude** [comment]
Yes, but do you actually have that programmer connected to your PC? If yes, download [Zadig](https://zadig.akeo.ie) and choose one of the libusb drivers to use for the AVRISPmkII.

**Comment by lwh456789** [comment]
yes

**Comment by lwh456789** [comment]
how to use Zadig

**Comment by lwh456789** [comment]
![捕获5](https://user-images.githubusercontent.com/63505637/79756508-4dd8dd80-834d-11ea-995e-4fb2dc8ad963.PNG)

**Comment by MCUdude** [comment]
You will have to click Options > List all devices. The select AVRISPmkII and select one of the libusb drivers

**Comment by lwh456789** [comment]
![捕获6](https://user-images.githubusercontent.com/63505637/79756841-d5265100-834d-11ea-9b08-c6286144ec31.PNG)

**Comment by lwh456789** [comment]
I'm sorry. Could you be a little more specific

**Comment by lwh456789** [comment]
I can't find AVRISP MKII

**Comment by MCUdude** [comment]
If you have an AVRISPmkII connected it will shop up in the drop-down menu where currently **Integrated camera** is selected.

**Comment by lwh456789** [comment]
![捕获7](https://user-images.githubusercontent.com/63505637/79757190-5251c600-834e-11ea-8196-1b1f5aea29cc.PNG)

**Comment by lwh456789** [comment]
but I cann't find it

**Comment by lwh456789** [comment]
what's the problem

**Comment by lwh456789** [comment]
The serial port that connects to my PC IS USB 2.0  serial

**Comment by MCUdude** [comment]
Well, you computer can't find your programmer. I can't help you with that. You can always have a look in the windows device manager to see if it shows up.

Just to make sure, you have THIS DEVICE connected, right?

![](https://www.microchip.com/_ImagedCopy/ATAVRISP2.jpg)

**Comment by lwh456789** [comment]
Like the Avr device you showed in the picture？I looked around my computer and didn't see the device you showed the picture on. Do I need to install this device for programming with AVRISPM KII？

**Comment by MCUdude** [comment]
OK, what do you want to do?

If you want to upload using the standard USB connector on your board, you just select your serial port and hit upload.

If you want to change other settings, like BOD or clock frequency, you will have to burn the bootloader. And for that, you **need a dedicated programmer** just like the one in the picture. If you don't have one, you cannot burn the bootloader.

If you absolutely have to do this, I recommend you get a USBasp programmer.

**Comment by lwh456789** [comment]
Yeah, I'M GONNA burn the bootloader to my MEGA 2560

**Comment by lwh456789** [comment]
Maybe I need to buy an AVRISPM KII right now?

**Comment by lwh456789** [comment]
In that case, after purchasing the AVRISPM KII device, I'll try burning the bootloader again，Thank you for your guidance

**Comment by MCUdude** [comment]
Yes do that. Or a USBasp programmer.
