### ISSUE TITLE
Print missing availableForWrite()

### ISSUE THREAD

**Issue by dzindra** [MCUdude/MiniCore#137]
Arduino core has `virtual int availableForWrite() { return 0; }` method in `Print` class, in MiniCore it is missing. Is it intentional or just an oversight?

**Comment by MCUdude** [comment]
Thanks for reporting. No, it's not intentional, I've just forgotten to add it. I will fix it soon!

**Comment by MCUdude** [comment]
Fixed in the latest release (2.0.5)
