### ISSUE TITLE
A6 & A7 fiix breaks digital 6&7

### ISSUE THREAD

**Issue by sim7755** [MCUdude/MiniCore#14]
I just got the update to get A6&7 working but it seems it has prevented digital 6 & 7 from working correctly. I have had a look but its a bit past my undertsading to work out.

**Comment by MCUdude** [comment]
Seems weird. Please post your code so I can test it myself

**Comment by MCUdude** [comment]
Anything?

**Comment by MCUdude** [comment]
I'm not able to reproduce this issue; Both digital pin 6 and 7 and analog pin A6 and A7 works just fine. 
I haven't gotten any reply from you either.
