### ISSUE TITLE
Use 7.3.0-atmel3.6.1-arduino7 to fix power.h for 328PB

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MiniCore#147]
Older versions of toolchain's power.h does not support the 328PB - this was one of the patches I got into that version!

**Comment by MCUdude** [comment]
But this is included in the latest IDE, so if they upgrade either their IDE or their Arduino AVR package they get the latest toolchain.

**Comment by SpenceKonde** [comment]
Ah, I see. 

IMO the requirement that the user have 1.8.13 of the IDE or 1.8.3 of the official megaAVR board package.

**Comment by SpenceKonde** [comment]
Er, I didn't ever finish that comment did I (was here looking for something unrelated).... that comment was meant to end in "should be documented"
