### ISSUE TITLE
SoftwareSerial on ATmega8?

### ISSUE THREAD

**Issue by beicnet** [MCUdude/MiniCore#15]
Hi,

Can you please implement somehow the "SoftwareSerial" support for the ATmega8 MCU?

Is it possible?

Kind regards,
Viktor

**Comment by MCUdude** [comment]
Try using the softwareSerial library found here: [https://github.com/MCUdude/MCUdude_libraries](https://github.com/MCUdude/MCUdude_libraries). It's using regular hrdware interrupts instead of PCINTs, which atmega8 doesn't have. The TX pin can be any pin you want, but the RX pin can only be pin 2 or 3 (INT0 or INT1)

**Comment by beicnet** [comment]
Thank for you quick response in a first place! ;)

In that case, can I use both of Serials at the same time, or?

Regards

**Comment by MCUdude** [comment]
> In that case, can I use both of Serials at the same time, or?

Yes, that's right. You can use the hardware serial as well as two software serial ports at the same time. That's three in total. Note that the library I linked to is modified and not well tested yet.

**Comment by beicnet** [comment]
Oh, great, thank you! :1st_place_medal:

**Comment by beicnet** [comment]
and a not related question, I can't find ATtiny85 Core on you Github, am I missing something?

**Comment by MCUdude** [comment]
I don't have any Arduino core for ATtiny85. Use [ATTinyCore](https://github.com/SpenceKonde/ATTinyCore)

**Comment by beicnet** [comment]
Ohh, sorry, I mixed you with that guy! :(

**Comment by MCUdude** [comment]
Did you fix this?

**Comment by beicnet** [comment]
Yes, everything seems fine!

Thank you again! ;)
