### ISSUE TITLE
Programming Mega8 without hardware programmer

### ISSUE THREAD

**Issue by KhArtNJava** [MCUdude/MiniCore#152]
Hello, guys.

I am trying to find out, how should I programm MiniCore to Atmega8 without hardware programmer.

I found phrase 
**_(If you're not planning to use the bootloader (uploading code using a USB to serial adapter), the FTDI header and the 100 nF capacitor on the reset pin can be omitted.)_**
at https://github.com/MCUdude/MiniCore#getting-started-with-minicore .

OK, I have USB to Serial adapter and I will connect it to Mega8 by this schematic diagram:
![image](https://user-images.githubusercontent.com/757085/92232180-c4b6e300-eeb6-11ea-8ecf-b1bd32f7ea72.png)

But what kind of programmer should I select in Arduino IDE?

![image](https://user-images.githubusercontent.com/757085/92232274-f334be00-eeb6-11ea-9493-33d15b73a15a.png)
Arduino as ISP, it's for case, if I'll use Arduino UNO as programmer.

But what I should select for programming with USB to serial adapter?

Thank you in advance.

**Comment by MCUdude** [comment]
Arduino IDE will only use the programmer (Arduino as ISP) when you run *Burn bootloader*. If you just click the upload button, and *Bootloader: Yes (UART0)* is selected, it will automatically try to upload using the USB to serial adapter. All you need to do is to select the right serial port under *Port*.
