### ISSUE TITLE
TinyWireS on ATmega8?

### ISSUE THREAD

**Issue by beicnet** [MCUdude/MiniCore#16]
Hi,

Can you please implement somehow the "TinyWireS" support for the ATmega8 MCU?

Is it possible?

I'm using rambo's library from https://github.com/rambo/TinyWire

Kind regards,
Viktor

**Comment by MCUdude** [comment]
> Can you please implement somehow the "TinyWireS" support for the ATmega8 MCU?

No. The ATmega8 already has hardwqare i2c support. If you want ATmega8 support you'll have to create an issue over at tihe TinyWire repo.
