### ISSUE TITLE
Arduino as ISP error I know the solution

### ISSUE THREAD

**Issue by joebonjovi** [MCUdude/MiniCore#165]
Hi I wanted to tell everyone when using Arduino as ISP there are some errors. The bootloader is good, just make sure you do not burn a 16mhz clock when you are using the internal oscillator, because you will have to reburn it with the 16mhz crystal OR IT WILL NOT WORK. I have bricked 3 of my chips accidentally burning 16mhz bootloaders on them now I have to wait until my order comes in. Also the core just overall does not work sometimes it says access denied and just does not upload. The solution to that is you need to upload the MiniCore bootloader, then you need to switch to programming device to The arduino you are using to upload to the IC, then you need to hold down shift and press the upload button. I spent days with this issue, I thought of it in my sleep and walah now it works.

**Comment by MCUdude** [comment]
It's true. You need to have an external clock before you set the fuses to use an external clock. You didn't brick the microcontroller though. It will respond again if you attach a crystal or similar.

If you screwed up and you don't have an external crystal, you can use [Adafruit's Arduino as ISP sketch](https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/ArduinoISP/ArduinoISP/ArduinoISP.ino). The only difference with this is that pin 9 outputs an 8 MHz clock that you can connect to the XTAL1 pin to recover the microcontroller.
