### ISSUE TITLE
Crystal frequency vs actual frequency

### ISSUE THREAD

**Issue by SYJONV2** [MCUdude/MiniCore#169]
I have problem with Atmega168 and Minicore. I'm setting in Arduino IDE "external 4MHz" but code runs 4x slower. Im sure that I'm using 4MHz resonator. Also shiftOut doesn't work properly.

**Comment by MCUdude** [comment]
4 MHz is 4x slower than 16 MHz, which is the default frequency a stock Arduino runs on. You will have to set the clock speed to 4 MHz in the IDE for it to work: Are you using a bootloader or an ISP for programming?

**Comment by SYJONV2** [comment]
I was using virgin Atmega, firstly I must burn bootloader even with ISP programming, now it works flawlessly.
