### ISSUE TITLE
Modbus problem

### ISSUE THREAD

**Issue by kamil-bit** [MCUdude/MiniCore#183]
When i want to use <ArduinoRS485.h> and <ArduinoModbus.h>
in example ModbusRTUClientToggle
https://www.arduino.cc/en/ArduinoModbus/ArduinoModbus
i get this 
\libraries\ArduinoRS485-master\src\RS485.cpp:181:18: error: 'SERIAL_PORT_HARDWARE' was not declared in this scope
 RS485Class RS485(SERIAL_PORT_HARDWARE, RS485_DEFAULT_TX_PIN, RS485_DEFAULT_DE_PIN, RS485_DEFAULT_RE_PIN);
                               
i set
atmega328
eeprom not retained
lto enabled
variant 328p 328pa
no bootloader

when i compile the same program on arduino uno or leonardo is well

**Comment by MCUdude** [comment]
What happens if you add `#define SERIAL_PORT_HARDWARE Serial` before including the library?

**Comment by kamil-bit** [comment]
Nothing again the same. I use 2.1.1 version of minicore

**Comment by kamil-bit** [comment]
Naprawiono

**Comment by kamil-bit** [comment]
Naprawiono
