### ISSUE TITLE
does this support atmega32u4?

### ISSUE THREAD

**Issue by youxiaojie** [MCUdude/MiniCore#199]
does this support atmega32u4?

**Comment by MCUdude** [comment]
Nope!

**Comment by youxiaojie** [comment]
do you have plan to support this chip?
I like yours rather than official:)
thanks!

**Comment by MCUdude** [comment]
Sorry, I have no plans to add any of the U2 or U4 chips. They are fundamentally different from the chips already supported by this core, and my time to create new Arduino cores is also very limited at the moment.
