### ISSUE TITLE
Arduino Pro Mini

### ISSUE THREAD

**Issue by chmasi** [MCUdude/MiniCore#200]
Hi,
Burning of the new Bootloader with MiniCore went quite fine, also uploading code to the new Arduino Pro Mini is working well.
Now I am struggeling, I have some code reading BME280 which works fine with the original Bootloader after I changed to 1MHz internal the BME will not be recognized anymore, init failed

Any suggestion how I can solve it? What did I wrong

BTW:
Reburning the original bootloader will bring back the BME to a working status again

**Comment by MCUdude** [comment]
The BME280 probably requires a higher i2c clock speed than the 1 MHz internal clock can offer. Use a different clock speed, and you should be all good.
