### ISSUE TITLE
Arduino Nano A6-A7 Broken

### ISSUE THREAD

**Issue by SConaway** [MCUdude/MiniCore#21]
On the Arduino Nano, A6-A7 are Broken.

**Comment by MCUdude** [comment]
OK? You haven't posted any description on how to reproduce the bug, nor any code.

The code below works just fine with my device:

``` c++
void setup() 
{
  Serial.begin(9600);
}

void loop() 
{
  int sensorValue = analogRead(A6);
  Serial.println(sensorValue);
  delay(100);
}
```

**Comment by SConaway** [comment]
You are right. I never noticed. Sorry.
