### ISSUE TITLE
Minicore makes a larger image than Arduino Uno setting.

### ISSUE THREAD

**Issue by wa2mze** [MCUdude/MiniCore#210]
I tried to build the code for this project: https://github.com/threeme3/usdx
When the sketch is compiled for the Arduino UNO it barely fits (98%) into the 32k space (with bootloader).
When the sketch is compiled for the ATMega328 under MiniCore it does not fit. (103%) with NO bootloader.
[usdx.zip](https://github.com/MCUdude/MiniCore/files/7614403/usdx.zip)

**Comment by MCUdude** [comment]
Have you turned on LTO?

LTO is on by default on UNO, but disabled by default in MiniCore.

**Comment by MCUdude** [comment]
Compiles just fine with LTO
