### ISSUE TITLE
Code size without bootloader not different?

### ISSUE THREAD

**Issue by pouriap** [MCUdude/MiniCore#216]
Whether I choose **Yes** or **No Bootloader** from the bootloader menu the code size reported by the IDE (when I click "verify") remains the same.

Is this normal behavior?

**Comment by MCUdude** [comment]
Does not happen to me using MiniCore v2.1.3.

**Comment by pouriap** [comment]
I updated to v2.1.3 and it's still happening.

**Comment by pouriap** [comment]
Ok so it's not the code size that is supposed to change after you enable/disable bootloader.
It's the **maximum** size that changes.

With bootloader selected: `Sketch uses 6654 bytes (86%) of program storage space. Maximum is 7680 bytes.`
Without no bootloader: `Sketch uses 6654 bytes (81%) of program storage space. Maximum is 8192 bytes.`

Thanks a lot @MCUdude
