### ISSUE TITLE
328PB OneWire Issue 

### ISSUE THREAD

**Issue by JoaquimBoavida** [MCUdude/MiniCore#218]
Hello,
I have a DS18B20 temperature sensor wired to PC2. I cannot make it work (not even detected) with onewire library.
The hardware is ok, because using another compiler (Bascom) works just fine. Can I use this pin? Or is another issue? What I'm doing wrong?

Thanks for any help.
Joaquim

**Comment by JoaquimBoavida** [comment]
Forgot to tell that I'm running @ 14.7456Mhz, so, no speed issue. One wire search returns nothing.

**Comment by MCUdude** [comment]
which Onewire library are you using? A link would be nice.

And I need a test sketch too so I can test it on my own hardware.
