### ISSUE TITLE
not working arduino pro mini..

### ISSUE THREAD

**Issue by kmb36td** [MCUdude/MiniCore#222]
tried to burn this bootloader through usbasp success.. but uploading using serial port dont work. not in sync... using original works.. i was hoping this boot loader would solve the pro mini boot loader wdt issue... there is also Wire.setWireTimeout error compiling pro mini skitch..

**Comment by MCUdude** [comment]
Sorry for the late reply. Do you have an 8 MHz or 16 MHz pro mini?

And can you share the Avrdude output when you're burning the bootloader, and when trying to upload?

**Comment by MCUdude** [comment]
No reply from OP. Assuming issue has been resolved
