### ISSUE TITLE
atmega328 wont RESET

### ISSUE THREAD

**Issue by plusmartin** [MCUdude/MiniCore#229]
<img width="212" alt="image" src="https://user-images.githubusercontent.com/2992915/182487453-682e9658-26e9-4240-a8eb-98abc62c08b3.png">

I cannot understand how is it possible to NOT beingg able to RESET the atmega328 when pulling the RESET pin LOW.
After burning the code using the above settings it runs once and then it crashes and I cannot RESET the board unless I cycle power.

Isnt the RESET pin supposed to work always? Can it be somehow bypassed or ignored?

**Comment by plusmartin** [comment]
If i press the RESET button while the code is still running then it does reset the sketch, but when it crashes it wont do anything.
I dont know if LTO should be enabled or disabled but it does the same issue on both cases.

**Comment by plusmartin** [comment]
In other words, how can I enable the RESET pin so that it works again? thanks

**Comment by MCUdude** [comment]
Are you able to burn the bootloader (set fuses) using an ISP programmer?

The Reset pin _can_ be configured as a GPIO, by clearing a bit in the low fuse memory. However, MiniCore does not disable the reset pin, but I don't know if you've been experimenting with the fuse bits or not...

You need a high-voltage programmer to recover a chip where the reset pin has been disabled, for instance an STK500 board.

**Comment by plusmartin** [comment]
I have the STK500. Do I need atmel studio to program this fuse? do you know what value it requires?

Does this mean that every time I burn de MiniCore bootloader I am effectively bypassing the RESET pin and cannot set it back unless I burn the fuse manually again with atmel studio? This would require two programming steps, which is very unfortunate.

**Comment by plusmartin** [comment]
Im sorry I misread your post. You state that MiniCore does NOT disable de reset pin, but for some reason my boards are not working using your bootloader.
Any suggestions on how to debug this? thanks

**Comment by MCUdude** [comment]
No response from OP. Highly likely it's a hardware issue.
