### ISSUE TITLE
Bootloader 168р

### ISSUE THREAD

**Issue by AFarkhad** [MCUdude/MiniCore#236]
Hi. can you help me for optiboot compiled for 168ра, UART0, baud 57600 external ocs at 16MHz, and led on pin B5. me need to work correctly with the НС-05 device. thanks in advance.

**Comment by MCUdude** [comment]
Here you go.

[optiboot_flash_atmega168p_UART0_57600_16000000L_B5.hex.zip](https://github.com/MCUdude/MiniCore/files/9792702/optiboot_flash_atmega168p_UART0_57600_16000000L_B5.hex.zip)
