### ISSUE TITLE
Compile fails when there is a space in the folder name

### ISSUE THREAD

**Issue by RaheelFarouk** [MCUdude/MiniCore#239]
The compile fails when there is a space in any of the folder names. 
**For example:** 
C:\Program Files\code\code.ino <- this will fail to compile
C:\Program_Files\code\code.ino <- this will compile successfully 

**Error from Arduino IDE:**
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

exit status 1

Compilation error: exit status 1

**Comment by harryberlin** [comment]
try "C:\Program Files\code\code.ino"

**Comment by RaheelFarouk** [comment]
I am using the compile button on the Arduino IDE Version 2.0.0

**Comment by Ziggy2013** [comment]
Arduino IDE 2.0 "improvements" at work.

**Comment by MCUdude** [comment]
This is a known issue and was fixed in 71fa421. I'll have to fix a new boards manager release to fix this.

**Comment by MCUdude** [comment]
MiniCore v2.2.0 is now available though boards manager!
