### ISSUE TITLE
To support ATmega328PB/168PB Xplained Mini on-board mEBDG programmer

### ISSUE THREAD

**Issue by mcuee** [MCUdude/MiniCore#243]
It will be good to add mEBDG programmer in MiniCore, as it is used in ATmega328PB-Xplained Mini and  ATmega168PB-Xplained Mini.

**Comment by mcuee** [comment]
BTW, the other Arduino Core which is supposed to work does not work at all in this case.
https://github.com/AtmelUniversityFrance/atmel-avr-xmini-boardmanagermodule/issues/12

**Comment by MCUdude** [comment]
Added in [a01ac07](https://github.com/MCUdude/MiniCore/commit/a01ac07a0e3e3d0f72c22b23c6c4942f91cd7edd)
