### ISSUE TITLE
twi_setFrequency1() function writes to wrong TWBR register

### ISSUE THREAD

**Issue by dewhisna** [MCUdude/MiniCore#244]
For the `Wire1` interface, such as on the ATmega328PB, the `twi1.c` file for `Wire1` writes to the wrong `TWBR` register here:

https://github.com/MCUdude/MiniCore/blob/95565897dbc3cd82f331b04b60f5b138ad517f43/avr/libraries/Wire1/src/utility/twi1.c#L127-L135

Interestingly, the comments are correct, yet the code writes to `TWBR` (which is mapped to `TWBR0` via `pins_arduino.h` to be the 0xB8 register) instead of `TWBR1` or the 0xD8 register.

Yet the code is correct in the `twi_init1` function for the default configuration.  However, there, the comments are wrong (and should also be updated):

https://github.com/MCUdude/MiniCore/blob/95565897dbc3cd82f331b04b60f5b138ad517f43/avr/libraries/Wire1/src/utility/twi1.c#L82-L87

This means that `Wire1` will always be running at the default frequency from init.  And any calls to `setFrequency` for `Wire1` will inadvertently be changing the frequency for `Wire` instead.

**Comment by MCUdude** [comment]
Thanks for reporting! I've just fixed the issue, and it will be available in the next boards manager release
