### ISSUE TITLE
Missing PORTE's PortNumber in tables in Wiring_refrence.md

### ISSUE THREAD

**Issue by LaZsolt** [MCUdude/MiniCore#247]
Not a big issue.
I think the tables should look like this:

`portNumber` - <i>byte/uint8_t</i> <br/>

| PortNumber  | Physical port |
|-------------|---------------|
| 0           | PORTA       ** |
| 1           | PORTB         |
| 2           | PORTC         |
| 3           | PORTD         |
| 4           | PORTE       *  |

 _* Only in PB variants_
 _** Not a valid port number_

**Comment by MCUdude** [comment]
Thanks! Fixed in https://github.com/MCUdude/MiniCore/commit/4184bd1fa08b78bb6a80fe575e1c78e1d458c6dd
