### ISSUE TITLE
Update HardwareSerial.cpp?

### ISSUE THREAD

**Issue by Arnold-n** [MCUdude/MiniCore#249]
Hi @MCUdude ,
Many thanks for this great project! Would it be possible to update HardwareSerial.cpp to the newest upstream version? I was bitten by [this retransmission bug](https://github.com/arduino/ArduinoCore-avr/commit/e9e43cf58302a16b606ed6fd0b5b2c73efc2ada2).

**Comment by MCUdude** [comment]
Thanks for pointing this out! I'm always open to bug fixes and improvements.

Would you like to create a PR in the MCUdude_corefiles repo? This is where the Arduino corefiles are hosted and are used with MiniCore, MightyCore, MegaCore, and MajorCore. Thanks!

https://github.com/MCUdude/MCUdude_corefiles

**Comment by Arnold-n** [comment]
Great, many thanks, super fast!
