### ISSUE TITLE
Optiboot 8.0 32 pin cpu versus Minicore ATmega328 compilation

### ISSUE THREAD

**Issue by Erik84750** [MCUdude/MiniCore#252]
Why can it be that a program written for ATmega328 would compile under Optiboot 8.0 boards definitions (32 pin cpu), but would not compile when setting the board definitions for Minicore ATmega328P?

This is what is set under Additional Boards Manager:
https://github.com/Optiboot/optiboot/releases/download/v8.0/package_optiboot_optiboot-additional_index.json

A very small part of the verbose error output is here:

[code]
In file included from C:\Users\Erik Arckens\Google Drive\documents\Arduino\Nextion_DCCEX_Controller_V1.2.9.1\Nextion_DCCEX_Controller_V1.2.9.1.ino:142:0:
C:\Users\Erik Arckens\Google Drive\documents\Arduino\Nextion_DCCEX_Controller_V1.2.9.1\Nextion_DCCEX_Controller_V1.2.9.1.ino: In function 'void setup()':
DCCEX_Throttle.h:125:21: error: 'Serial1' was not declared in this scope
     #define nextion Serial1

[/code]

EDIT: these are the current program processor definitions used,and that do work for the Optiboot 8.0 board definitions;
Could it be they are to be different for the Minicore?

#if defined (ARDUINO_AVR_LEONARDO)
#define AVR_UNO
#elif defined (ARDUINO_AVR_UNO)
#define AVR_UNO
#elif defined (ARDUINO_AVR_PRO)
#define AVR_UNO
#elif defined (Arduino_AVR_ATmega328)
#define AVR_UNO
#elif defined (ARDUINO_AVR_NANO)
#define AVR_UNO

**Comment by harryberlin** [comment]
328 does not have Serial1, only 328PB

**Comment by Erik84750** [comment]
True, but this error is due to the wrong board definition being selected in the #if defined section.

So my question stands: what should be the correct syntax in my board definitions code for it to select the proper ATmega328P board when using MCUdude's board definitions?

**Comment by Erik84750** [comment]
solved:
#elif defined (ARDUINO_AVR_ATmega328)
#define AVR_UNO
