### ISSUE TITLE
ATMega8L bootloader not working with Internal RC 8 and 4 MHz

### ISSUE THREAD

**Issue by VitinLima** [MCUdude/MiniCore#256]
When burning the bootloader in the ATMega8L for uploading code with Serial USART, it works fine with External crystal 16MHz, and works fine with Internal RC with 1MHz and 2MHz, but when uploading a simple Blink code with Internal RC 8MHz and 4MHz, the arduino IDE gave me an error

avrdude: Version 7.1-arduino.1
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is ~\AppData\Local\Arduino15\packages\MiniCore\hardware\avr\2.2.2\avrdude.conf

         Using Port                    : COM5
         Using Programmer              : arduino
         Overriding Baud Rate          : 38400
avrdude stk500_getsync() error: cannot communicate with device: resp=0xfc
avrdude main() error: unable to open programmer arduino on port COM5

avrdude done.  Thank you.

the selected serial port 
 does not exist or your board is not connected

I really cant find whats wrong, the connections are the same and it works with other configurations, I wanted to use internal RC for having more IO pins, and 8MHz because timing is important in my applications...
Please help? If you need more info I'll gladly supply
Thanks in advance

**Comment by TomaszKilianczyk** [comment]
unfortunately, the internal rc has too little accuracy to be able to communicate properly, therefore in these microcontrollers it is required to use an external rc for communication serial port the best cristal is 11.0592 for good communication
