### ISSUE TITLE
The microcontroller model on the picture error

### ISSUE THREAD

**Issue by czghzc** [MCUdude/MiniCore#26]
The microcontroller model on the picture error

![687474703a2f2f692e696d6775722e636f6d2f736443444562592e6a7067](https://user-images.githubusercontent.com/23645596/33643218-b4cd7b02-da78-11e7-9c4c-9924edba1198.jpg)

It should be Atmega168, not Atmega128
Another picture is also

**Comment by MCUdude** [comment]
Should be ok now 👍
