### ISSUE TITLE
Atmega328 and IR sensor.

### ISSUE THREAD

**Issue by Adeeva01** [MCUdude/MiniCore#268]
I tried the code to turn the LED off and on using the code example in the irremote library, simple receive. The sensor can read the IR signal, but cannot turn on the LED, the LED only blinks. I have used 2 sensors and 2 remotes, the results are the same. how to fix it?. Thank You. i am using atmega328, ch340 and ide 1.8.19.
[Atmega328 IRsensor IRremote library](https://youtu.be/UTwr4VuHmS0?si=TJDv5Uzq-OaX7jbG)

**Comment by MCUdude** [comment]
You you post the code you're using?

**Comment by Adeeva01** [comment]
Thank You. the code can run fine. after changing the pin. the led doesn't light up if using pin 13.
