### ISSUE TITLE
Timing on Atmega88 8Mhz Internal is wrong

### ISSUE THREAD

**Issue by Rabujan** [MCUdude/MiniCore#27]
The timing on the atmega88 at 8mhz internal is wrong. delay(1000); is ~7 seconds.
Works great at other frequencies.

**Comment by MCUdude** [comment]
Hmm. Not so sure about this.. Have you tried hitting "Burn Bootloader" to set the correct fuses for the 8 MHz internal oscillator? Sounds like the microcontroller runs at 8 MHz while the code is compiled for 8 MHz operation

**Comment by Rabujan** [comment]
Thanks for answering so fast. You were right I forgot to to hit burn bootloader first. It works great now.

Thanks

**Comment by MCUdude** [comment]
Great to hear you sorted it out 👍
