### ISSUE TITLE
Problems with atmega 328pb and minicore?

### ISSUE THREAD

**Issue by serlancelot** [MCUdude/MiniCore#283]
Hello! I have a problem... I'll tell you...
I have made a program that works on Arduino Uno, it only uses the EEPROM library, the rest of the functions are "normal", digitalWrite, Millis, If and case (maybe some more). The problem is that when I put this program on a 328pb it works partially but if I put it on a 328p (both without bootloader, I load the hex with another programmer) it works perfectly for the 328pb I use the minicore and select the pb, for the 328p I select arduino uno board. My question is, could it be a minicore problem? The IDE version is 2.1.0 and the minicore is 3.0.
The solution is to use the atmega328p, but the problem is that now I have several atmega328pb on the bench.
Thanks greetings!

**Comment by MCUdude** [comment]
It may be your hardware. The ATmega328PB isn't very "good" at driving external oscillators/crystals, so the most reliable option is to use a dedicated oscillator that drives the XTAL1 pin in the 328PB. However, if you use the internal oscillator, or should be OK. I highly doubt it's a MiniCore-related problem.
