### ISSUE TITLE
Clock options for ATMega328P are ambiguous

### ISSUE THREAD

**Issue by Rob190** [MCUdude/MiniCore#287]
For example if I select 'External 8Mhz', the documentation says "8MHz External crystal/oscillator | Common clock when working with 3.3V" but according to the datasheet this could mean:

1. Full Swing Crystal Oscillator
2. Low Power Crystal Oscillator  8.0 - 16.0 MHz
3. External clock

These are distinct configurations so which one applies?

**Comment by MCUdude** [comment]
The fuses selects the full swing oscillator option. This is by far the most forgiving one, and are able to drive pretty much every crystal+capacitor(s) combination. The ATmega328PB does not have a full swing oscillator option, and is much, much more flakey when it comes to the oscillator circuity.
