### ISSUE TITLE
[feature] New 9.216MHz to Supported clock frequency. 

### ISSUE THREAD

**Issue by rkierzek** [MCUdude/MiniCore#290]
Please add additional frequency for external XTAL **9.216MHz**
I want to UART-friendly value below 10MHz and more than 7.3728MHz(already supported)
For ATmega168V I I don't want to over-extend datasheet values (nearest supported by MiniCore 11,0592MHz) but additional 25% computing power is non-trivial value.
Regards

**Comment by MCUdude** [comment]
Thanks for the suggestion! Implemented in MiniCore v3.0.2, available in the Arduino boards manager
