### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mlksahib** [MCUdude/MiniCore#292]
I am trying to upload bootloader to new atmega328p-smd version but ide shows (in verbose output) syntax error in avrdude.conf file at line 421. 
Another error is that the said file (avrdude.conf) can't be opened
I am using IDE version 1.8.19, windows 10 pro OS 

P.S: previous core with optiboot bootloader also can't upload any code to new microcontroller now although i am able to upload code to any previously programmed microcontroller. This has happened before but at that time i tried to upload from another computer (windows 7) and it worked on other computer fine. Now i can't upload from any computer

**Comment by MCUdude** [comment]
It would help if you shared the actual Avrdude output.

Which version of MiniCore do you currently have installed?

**Comment by mlksahib** [comment]
Right now i don't have access to my work pc. I will share it tomorrow. (It's night time in my country)
Syntax error is related to miniCore 3 (with urboot version). I downloaded it today morning  .  Verbose output shows just 2 lines, 1st line is syntax error at line 421 of avrdude.cofg 
2nd line is avrdude.cofg can't be opened

**Comment by mewec** [comment]
I've just hit the same problem trying to upload code to pre bootflashed 328

Here's the verbose uploaded output

Arduino: 1.8.19 (Windows 10), Board: "ATmega328, Yes (UART0), EEPROM retained, Default, 328P / 328PA, BOD 2.7V, LTO disabled, Internal 8 MHz"

Sketch uses 15180 bytes (46%) of program storage space. Maximum is 32384 bytes.

Global variables use 65 bytes (3%) of dynamic memory, leaving 1983 bytes for local variables. Maximum is 2048 bytes.

C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude -CC:\Users\Mike\Documents\Arduino\hardware\MiniCore\avr/avrdude.conf -v -patmega328p -curclock -PCOM1 -b38400 -D -xnometadata -Ueeprom:w:C:\Users\Mike\AppData\Local\Temp\arduino_build_208537/HC4x4x4_Animation.ino.eep:i -Uflash:w:C:\Users\Mike\AppData\Local\Temp\arduino_build_208537/HC4x4x4_Animation.ino.hex:i 



An error occurred while uploading the sketch

avrdude: Version 6.3-20190619

         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

         Copyright (c) 2007-2014 Joerg Wunsch



         System wide configuration file is "C:\Users\Mike\Documents\Arduino\hardware\MiniCore\avr/avrdude.conf"

avrdude: error at C:\Users\Mike\Documents\Arduino\hardware\MiniCore\avr/avrdude.conf:421: syntax error

avrdude: error reading system wide configuration file "C:\Users\Mike\Documents\Arduino\hardware\MiniCore\avr/avrdude.conf"

**Comment by MCUdude** [comment]
You need to install the lastest Minicore version from the **boards manager**. That will also install Avrdude 7.2, which is required.

**Comment by mewec** [comment]
Thanks for the prompt response.
I had manually installed from the zip.
Mike

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Amperogeddon** [comment]
Hi guys!
I also encountered a similar problem. I tried reinstalling the IDE, changing the avrdude.conf file, installing different versions of the IDE and MiniCore - it didn't help.
I couldn’t do it without your help, thank you very much in advance!

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\parshikovsv\Documents\Arduino\hardware\MiniCore-3.0.1\avr/avrdude.conf"
avrdude: error at C:\Users\parshikovsv\Documents\Arduino\hardware\MiniCore-3.0.1\avr/avrdude.conf:421: syntax error
avrdude: error reading system wide configuration file "C:\Users\parshikovsv\Documents\Arduino\hardware\MiniCore-3.0.1\avr/avrdude.conf"
There was an error loading https://downloads.arduino.cc/packages/package_index.json

**Comment by MCUdude** [comment]
> avrdude: error at C:\Users\parshikovsv\Documents\Arduino\hardware\MiniCore-3.0.1\avr/avrdude.conf:421: 

Remove the manually installed MiniCore version and install the whole thing though the boards manager instead. The problem is that the Avrdude version that's bundled with the IDE is too old to parse the Avrdude.conf file that MiniCore uses.

**Comment by Amperogeddon** [comment]
Thanks for the quick response!
The thing is that I can’t use the board manager because I don’t have access to the Internet. Internet access is only available from a remote desktop. Is there a way to fix this error without using a board manager?
Thank you very much in advance!

**Comment by MCUdude** [comment]
You'll either have to manually replace the Avrdude executable with 7.2, or download MiniCore v2.x instead, which uses Avrdude 6.3

**Comment by Amperogeddon** [comment]
Thank you very much for your answer!
I apologize in advance for what is probably a stupid question. But how to do that?

**Comment by MCUdude** [comment]
Download the latest v2.x version here (zip file), and install it manually, as described in the README. That should hopefully _just work_.
