### ISSUE TITLE
Trying to enlarge pinout diagrams in README fails with 'Non-Image content-type returned'

### ISSUE THREAD

**Issue by fritzlb** [MCUdude/MiniCore#293]
When trying to enlarge the pinout diagrams in REDAME by clicking them, a new tab opens with nothing but an error "Non-Image content-type returned".
I could reproduce the error with firefox (Windows) and Safari (iOS), so I'm going to assume it's the website and not my device configuration.

**Comment by MCUdude** [comment]
All of the pinouts can be enlarged on my phone. It may be a Github related issue. Please try again

**Comment by fritzlb** [comment]
Interesting, now it works for me too. I’ll save them to my computer, just in case something like this happens again. Thanks for the fast reply!
