### ISSUE TITLE
burn bootloader to mega88 fail

### ISSUE THREAD

**Issue by koyoi** [MCUdude/MiniCore#302]
to fix, add
C:\Users\xxxx\AppData\Local\Arduino15\packages\MiniCore\hardware\avr\3.0.1\boards.txt
at line 497
88.menu.bootloader.uart0.bootloader.extended_fuses=0xfc

at line around 497
88.menu.bootloader.no_bootloader.bootloader.extended_fuses=0xfd

**Comment by MCUdude** [comment]
Hi! It's a known issue and was resolved in d46c83fca2612e66d3059f8bb8277ee56bf20d72.
I just haven't released a new version yet. But it's probably about time.
