### ISSUE TITLE
Uploading error : given error when upload to Arduino UNO r3 using mobile app Arduino studio on

### ISSUE THREAD

**Issue by Deepakkumargarg** [MCUdude/MiniCore#304]
name.anton smirnov.arduinostudio: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent beint needs to be used with inline replies or bubbles.

**Comment by Deepakkumargarg** [comment]
Kindly help , how to solve this error on mobile , compilation is done , error while uploading only

**Comment by MCUdude** [comment]
Sorry, I don't offer any support for mobile apps. That would be the app developers responsibility to support 3rd party cores like this one.
