### ISSUE TITLE
Not compile error "Compilation error: 'LED' does not name a type"  Atmega168 include CPP with class declaration.

### ISSUE THREAD

**Issue by grig27** [MCUdude/MiniCore#305]
Use Arduino IDE 2.3.2
Select board Atmega168.

In code write #include "LED.cpp" with declaration class "class LED".

Use class LED as "LED LEDS[3];"

In compile error - 
Compilation error: 'LED' does not name a type.

Source code included https://github.com/docdawning/Illuminatrix/blob/master/Illuminatrix-Arduino/ino/src/sketch.ino

**Comment by MCUdude** [comment]
`LED` is a built-in constant you can't use for anything else that the built-in LED constant.

https://github.com/MCUdude/MiniCore/blob/0bb50f6a6648e37cbe53012c61322345847c2a03/avr/variants/standard/pins_arduino.h#L105

**Comment by grig27** [comment]
Change LED to LEDCLASS fine work!
