### ISSUE TITLE
Consider Travis CI testing for MiniCore?

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MiniCore#31]
MiniCore is slowly getting more and more popular, and with the recent changes with MCUdude_corefiles, I think adding Travis CI to MiniCore should be considered?

Would you like to help me out with this one too @per1234 ? 🙂

**Comment by per1234** [comment]
OK, will do.

Please create a branch named MiniCore in your CI-reports repository and enable Travis CI builds of MiniCore according to these instructions:
https://github.com/MCUdude/MightyCore/issues/57#issuecomment-358134994

**Comment by MCUdude** [comment]
Thanks!
I've followed the instructions, so everything should be ready 👍
