### ISSUE TITLE
ReadMe pictures broken links 

### ISSUE THREAD

**Issue by vergo77** [MCUdude/MiniCore#310]
If I click on the ReadMe pictures I get this error:

![image](https://github.com/user-attachments/assets/7fa95472-c57b-4f37-b9d3-3bd92a170b23)

W10, MS Edge

**Comment by MCUdude** [comment]
Sorry, but I can't reproduce the issue. It works great here using both Edge and Chrome

**Comment by tszebeni** [comment]
Hi experience the same issue, but also found a workaround @vergo77  you may also be interested: right click over the small image and save as image... my browser can save it in a proper format that way.

**Comment by MCUdude** [comment]
Doesn't seem to be a problem anymore.
