### ISSUE TITLE
Broken link to Pinout picture 

### ISSUE THREAD

**Issue by ar-numa** [MCUdude/MiniCore#311]
Klicking on the pinout picture "TQFP-32 SMD package ATmega48/88/168/328PB" (under paragraph Pinout) delivers an empty page and the message: "Non-Image content-type returned".

**Comment by tszebeni** [comment]
Hi experience the same issue, but also found a workaround @ar-numa you may also be interested: right click over the small image and save as image... my browser can save it in a proper format that way.

**Comment by MCUdude** [comment]
Is this still an issue?
