### ISSUE TITLE
USBtiny ISP Programmer not working anymore (since MiniCore v2.2.0 and newer)

### ISSUE THREAD

**Issue by gu9154** [MCUdude/MiniCore#320]
Hello,
I have an Adafruit USBtiny ISP programmer. I failed to burn an ARDUINO Bootloader to an ATmega 8 with the lates Version of MiniCore. 
I tried downgrading to fix the issue. Finallay, with MiniCore v2.1.3, I was abled to burn the bootloader successfully.
I made sure that it is not a programmer or driver issue. I borrowed an other USBtiny programmer from a friend - same result. I was using Windows 11, Libusb-32 adafruit_drivers_2.5.0.0.exe and Arduino IDE 2.3.3. Burning a bootloader to an ArduinoUNOboard (ATmega328p) was working fine all the time. Downgrading Arduino IDE to 1.8.0 did not help or solve the issue.
This was the Arduino warning/error message with Minicore V2.2.0 and newer:

avrdude: Version 7.1-arduino.1
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is C:\Users\Max\AppData\Local\Arduino15\packages\MiniCore\hardware\avr\2.2.0\avrdude.conf

         Using Port                    : usb
         Using Programmer              : usbtiny
avrdude: usbdev_open(): found USBtinyISP, bus:device: 001:031
avrdude usbtiny_open() warning: cannot open USB device: Permission denied
avrdude usbtiny_open() error: cannot find USBtiny device (0x1781/0xc9f)
avrdude main() error: unable to open programmer usbtiny on port usb

avrdude done.  Thank you.

Failed chip erase: uploading error: exit status 1

I think it is a serious issue since it renders the Adadfruit USBtiny Programmer completely useless with newer versions of MiniCore.
Hope you can fix it.

Best regard
Max Nagel

**Comment by MCUdude** [comment]
See this forum thread. https://forum.arduino.cc/t/solved-for-usbasp-avrdude-usbopendevice-warning-cannot-open-usb-device-permission-denied/1175993

> I solved the following problem before I reached the point of posting but I thought it might be worth posting anyway so someone else might solve the problem more quickly than I did. The solution was to use Zadig to change my USBasp driver from libusb-win32 to libusbK.

USBasp and USBtinyISP both uses libusb
