### ISSUE TITLE
[Suggestion] CH340 and FT232 programmers

### ISSUE THREAD

**Issue by Monniasza** [MCUdude/MiniCore#321]
Hi. I'm thinking about reflashing the bootloader on an Arduino Nano clone. It uses CH340 interface chip, and I also have the FT232 programmer board. Currently, no programmer option works with the clone. I'd be grateful if you add support for the programmers.

**Comment by MCUdude** [comment]
FT232 and CH340 are just USB to UART chips. They will only work for uploading new programs as long as the microcontroller has a bootloader present. All you do is select the correct COM port that the CH340 or FT232 represents on your computer

**Comment by Monniasza** [comment]
Do I have to have separate Arduino as a programmer?

**Comment by MCUdude** [comment]
Either that, or a dedicated programmer, such as a USBasp or a USBtinyISP, which is what I'd recommend, since using "Arduino as ISP" is a bit fiddly and is usually unreliable due to its DIY nature

**Comment by Monniasza** [comment]
My USBasp isn't recognized as a serial device. By the way, I use Linux Mint and Arduino IDE on Flatpak.

**Comment by MCUdude** [comment]
The USBasp is not a serial device, so it will not show up as a serial device.

You'll have to select the appropriate settings and hit "Burn bootloader" after you've selected "USBasp" or "USBasp slow" under the "Programmers" menu.

<img width="502" alt="bilde" src="https://github.com/user-attachments/assets/87a2bed5-5345-4e9e-aef5-e1bd5f7c11a0">
