### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by spa-sam** [MCUdude/MiniCore#40]
Watchdog not work!
Atmega328p. If Watchdog is triggered then the microcontroller restarts and freeze (or enters the reboot cycle?!). It does not depend whether there is a bootloader or not.

#include <avr/wdt.h>

void setup() {
wdt_reset();
wdt_enable(WDTO_8S);
wdt_reset();
//my prog
}
void loop() {
wdt_reset();
//my prog
}

Without Watchdog, everything works fine!

**Comment by MCUdude** [comment]
I'm on vacation right now, but I'll be home this weekend. Will have a look at this soon 👍

**Comment by spa-sam** [comment]
I'm sorry! It turned out to be problematic in the U8glib library. 
The display of the Nokia 5110 with the library from Adafruit wdt works.

**Comment by MCUdude** [comment]
Great!
