### ISSUE TITLE
Travis is failing due to library changes

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MiniCore#55]
I thought it may be a good idea to re-structure the libraries so the user never actually has to include SPI1.h or Wire1.h. This means there does not exist any examples for Wire1 and SPI1 anymore.

Would you like to help me out on this one @per1234 ?

**Comment by per1234** [comment]
Looks good! That simplifies the Travis CI config significantly. I think I have it all fixed up.

I also noticed the Travis CI build hadn't been updated after the addition of the EEPROM library so I added some missing library jobs.

The build is in progress. I'll submit the PR as soon as I verify all is working.
