### ISSUE TITLE
ATmega328pb efuse bit 3 can be added to avrdude config

### ISSUE THREAD

**Issue by epccs** [MCUdude/MiniCore#61]
The bit is for clock failure detection. Unfortunately one of the parts I got from Digikey had the fuse set so I had to figure out how to get avrdude to input it during writing so it could be cleared.

```# efuse bit 3 can be added. It is for clock failure detection
part parent "m328"
    id			= "m328pb";
    desc		= "ATmega328PB";
    signature		= 0x1e 0x95 0x16;

    ocdrev              = 1;
    
    memory "efuse"
        size = 1;
        min_write_delay = 4500;
        max_write_delay = 4500;
        read = "0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0",
               "x x x x x x x x o o o o o o o o";

        write = "1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0",
                "x x x x x x x x x x x x i i i i";
    ;
;
```

**Comment by MCUdude** [comment]
Thanks for reporting! It seems like I'll have to apply a similar fix to ATmega324PB as well. However it's kinda weird the the rest of the *PB family (48PB/88PB/168PB) doesn't have CFD at all..

> Unfortunately one of the parts I got from Digikey had the fuse set so I had to figure out how to get avrdude to input it during writing so it could be cleared.

That's weird. I have an ATmega324PB I ordered from Digikey. CFD was also enabled on this one, even though the datasheet says it should be turned off by default.
