### ISSUE TITLE
How to use space from not burning bootloader?

### ISSUE THREAD

**Issue by positron96** [MCUdude/MiniCore#66]
Hello. I am trying to compile a hefty program for a Atmega 8. It is larger that its memory and I get

```ld.exe: region `text' overflowed by 90 bytes``` message. 

Then I try compile it with bootloader disabled (by selecting respective option from IDE menu) but get the same 
```ld.exe: region `text' overflowed by 90 bytes``` error.

How can I make use of space left from not burning a bootloader?

BTW, if I compile for attiny85 (using https://github.com/SpenceKonde/ATTinyCore), the firmware fits totally fine and I get ```Sketch uses 6318 bytes (77%) of program storage space. Maximum is 8192``` message. Is there a way to tweak options for minicore to get similar result?

**Comment by MCUdude** [comment]
Have you tried enabling LTO?

**Comment by positron96** [comment]
Yes, these are results with LTO enabled.

**Comment by MCUdude** [comment]
The maximum size when compiling with **Bootloader: No** is 8192 bytes, and 7680 bytes when **Bootloader: Yes** is selected. Does yours say 7680 no matter what you choose?

**Comment by positron96** [comment]
This is code for Nrf41L01 mesh network (courtesy of https://github.com/nRF24/RF24Mesh/issues/138 ). It requires libraries RF24, RF24Network and RF24Mesh, all of them available in Arduino Library manager.
```
#define CE_PIN 3
#define CSN_PIN 3 //Since we are using 3 pin configuration we will use same pin for both CE and CSN

#include "RF24.h"
#include "RF24Network.h"
#include "RF24Mesh.h"

/**** Configure the nrf24l01 CE and CS pins ****/
RF24 radio(CE_PIN, CSN_PIN);
RF24Network network(radio);
RF24Mesh mesh(radio, network);
/**
   User Configuration: nodeID - A unique identifier for each radio. Allows addressing
   to change dynamically with physical changes to the mesh.

   In this example, configuration takes place below, prior to uploading the sketch to the device
   A unique value from 1-255 must be configured for each node.
   This will be stored in EEPROM on AVR devices, so remains persistent between further uploads, loss of power, etc.

 **/
#define nodeID 1


uint32_t displayTimer = 0;

struct payload_t {
  unsigned long ms;
  unsigned long counter;
};

void setup() { 
  // Set the nodeID manually
  mesh.setNodeID(nodeID);
  // Connect to the mesh
  mesh.begin();
}

uint32_t ctr = 0;

void loop(){
  mesh.update();

  // Send to the master node every second
  if (millis() - displayTimer >= 1000) {
    ctr++;
    payload_t payload = {millis(), ctr};

    // Send an 'M' type message containing the current millis()
    if (!mesh.write(&payload, 'M', sizeof(payload))) 
    {

      // If a write fails, check connectivity to the mesh network
      if ( ! mesh.checkConnection() ) 
      {
        mesh.renewAddress();
      }
    }
    displayTimer = millis();
  }
}
```

**Comment by positron96** [comment]
My Arduino is 1.8.5, MiniCore version is 2.0.1, Arduino AVR Boards 1.6.20

**Comment by MCUdude** [comment]
Well, I was able to compile without any isses..

<img width="873" alt="skjermbilde 2018-08-09 17 06 08" src="https://user-images.githubusercontent.com/3238730/43907792-9a505232-9bf6-11e8-9b8b-b631168d74ab.png">

<img width="330" alt="skjermbilde 2018-08-09 17 07 00" src="https://user-images.githubusercontent.com/3238730/43907808-a4acc59e-9bf6-11e8-9fb9-4ac9bb6964aa.png">

**Comment by MCUdude** [comment]
Here's what you can do. Open Arduino IDE settings, and paste this boards manager URL:
`https://downloads.arduino.cc/packages/package_avr_3.6.0_index.json`

Then open the boards manager and upgrade Arduino AVR boards to 1.6.207. This downloads a newer compiler version.

**Comment by positron96** [comment]
Ok, so, this did help me. Thank you!
I now get the elf with 8174 that fits into flash without bootloader, though by a small margin (99%).

So, do you say that old compiler did not want to cramp the code into ELF while new one does?

**Comment by MCUdude** [comment]
It seems like the new compiler optimized the code even more, and that's why it bare fits now.

**Comment by MCUdude** [comment]
Even though MiniCore and ATtinyCore may look more or less the same, there's clear differences under the hood. ATtinyCore is more optimized because many "Arduino functions" are written from scratch.
MiniCore on the other hand is more or less generic "Arduino code" that's been tweaked to run on other AVRs as well.
