### ISSUE TITLE
Optiboot bootloader not responding

### ISSUE THREAD

**Issue by macdonaldtomw** [MCUdude/MiniCore#68]
Hello,

I'm trying to write an app that will turn an Arduino into a stand-alone STK500 programmer that will flash decode a .hex file stored on a connected SD card, and then flash that hex file to a ATmega328PB that is connected to the Arduino via UART using STK500 protocol (communicating directly with Optiboot bootloader).  See below image:

![image](https://user-images.githubusercontent.com/6575957/45890530-960ed300-bd99-11e8-87d7-8cab8f6593a4.png)

Here are the steps I am following:

1) Connect USBTiny ISP to my PC and to my ATmega328PB board via ISP header
2) Select "burn bootloader" command from within Arduino IDE:  _Tools-> Burn Bootloader_  
3) Verify bootloader was successfully flashed to ATmega328PB using the status window in Arduino IDE
3) Disconnect ISP header from my ATmega328PB board
4) Connect my Particle Electron to the ATmega328PB board (only signals are UART_TX, UART_RX... and common ground)
5) Run app on Particle Electron that resets the ATmega328PB using an external watchdog-based reset circuit connected to UART_TX signal (hold UART_TX low for >0.8seconds will pull ATmega328PB reset line LOW), and then immediately attempts to read the signature bytes from the ATmega328PB using the STK500 _READ_SIGN_ command  (sends 0x75, 0x20  bytes --> STK_READ_SIGN, CRC_EOP)

Nothing happens (I get no response from the ATmega328PB).

Here is a logic analyzer connected to UART signals as well as the reset signal of the ATmega328PB.

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/6575957/45890930-93f94400-bd9a-11e8-88ec-6ca13b4e9198.png)
![image](https://user-images.githubusercontent.com/6575957/45890947-a5425080-bd9a-11e8-984d-de345bbf70d6.png)

Here is the same process I just described, except instead of sending _STK500_READ_SIGN_ immediately, there is a 200 ms delay inserted to allow the ATmega some breathing room after reset:

![image](https://user-images.githubusercontent.com/6575957/45891141-30bbe180-bd9b-11e8-80ee-9d7705230277.png)
![image](https://user-images.githubusercontent.com/6575957/45891158-46c9a200-bd9b-11e8-9c07-781ded98b733.png)

As you can see, there is no difference.

One strange thing that I note however is that the TX line of the ATmega (i.e. HOST_RX signal in logic analyzer screenshots) gets pulled low for about 2.5µs **before** the ATmega RST line gets released.  This phenomenon is present no matter how long I hold the ATmega reset line LOW... it always appears about 10-15 µs _before_ the reset line gets released.... like it knows that its about to be released or something...

**Comment by MCUdude** [comment]
I've never used Optiboot with anything else that a USB to serial adapter, so I don't know what's wrong with your setup.
 I'd start out by uploading a hex file to the ATmega328PB using a USB to serial adapter, and capture the whole session with a logic analyzer. Then I'd switch back to your setup and try again, just to compare the two.

However a logic analyzer doesn't capture "real" voltages. It therefore may be an issue with the threshold voltages.

**Comment by MCUdude** [comment]
Did you ever solve this?

**Comment by macdonaldtomw** [comment]
I did!

**Comment by MCUdude** [comment]
Awesome!
