### ISSUE TITLE
Killed a bunch of Arduino Pro Mini with the 1Mhz option

### ISSUE THREAD

**Issue by slave2anubis** [MCUdude/MiniCore#72]
Hi, just found this nice bootloader, and its just what i am needind in my ultra low power sensor application. After using a USBAsp to program a Arduino Pro Mini with the 8Mhz internal clock option, everything worked as expected... the LED (PIN13) did a heart beat kinda blinking.
But i was after the 1Mhz clock option since it, makes sense to get as low clock as posibile, sadly  after burinng the bootloader again using this option the board died, tried on a few other ones the same issue... Working fine on 8Mhz but dying after the 1Mhz flash.
Any hints on what i am doing wrong?

Thanks.

**Comment by MCUdude** [comment]
Hi!
I think I know what's wrong. You see the ISP clock frequency of the USBasp is on many cases higher that on other programmers. The rule is that the ISP clock should be a maximum of 1/4 of the clock the microcontroller runs on. My USBasp has an ISP clock of around 730kHz, which is WAY to high to interface with a microcontroller running at 1 MHz.

What you need to do is to add an extra parameter to the AVRdude command `-B[divider]`. I use `-B32` to run the USBasp at 1/32th of the speed. The simplest way of doing this is to install [MicroCore](https://github.com/MCUdude/MicroCore), which moved you a set of "slow" programming options such as _USBasp (slow)_.

<img width="603" alt="skjermbilde 2018-11-06 08 51 33" src="https://user-images.githubusercontent.com/3238730/48050106-37fb4b00-e1a1-11e8-9786-c9c6762eecba.png">

**Comment by slave2anubis** [comment]
Thank's man! Been abel to resurect 2 out of the 3 with this method, and get them to work perfectly at 1Mhz internal clock.
