### ISSUE TITLE
delay() on 20Mhz is wrong

### ISSUE THREAD

**Issue by Jackjan4** [MCUdude/MiniCore#78]
Since MiniCore uses the original wiring.c (I suppose?), delay is off when not using frequencies that are fractions of 64. 20Mhz is obviously not a fraction of 64 and gives wrong delay timings when used.
Simple LED tests can show how timing drafts away compared to 16Mhz (external in the Uno for example) or 8Mhz internal.

The problem resides in the return statement of micros() which returns an int, however the division result is a fraction.

The problem is quite difficult, since it needs an elegant solution that doesn't add much overhead so delay() is off on all devices.

EDIT: A possible solution could be to count how much of a fraction we lost each time and when this fraction reaches 1 (or higher integers) we add them. I could test & implement such a solution if the philosophy of this core allows changes in the corefiles. (I'm still a newcomer here)

**Comment by MCUdude** [comment]
I am aware if the issue. All my Arduino cores uses standard wiring.c. Feel free to issue a pull request [here](https://github.com/MCUdude/MCUdude_corefiles) if you're able to come up with something better for 20 and 24 MHz

**Comment by Jackjan4** [comment]
Since this is a topic for the corefiles then I will close this and open an issue [there](https://github.com/MCUdude/MCUdude_corefiles/issues/13).
