### ISSUE TITLE
Add bootloader support for 24MHz

### ISSUE THREAD

**Issue by Jackjan4** [MCUdude/MiniCore#80]
24MHz is the next common frequency after 20MHz and the atmegas are running really stable with it. (Even though it is not specified in the datasheets)
So we should compile bootloaders for it and add a menu setting. 
Additionally some core functions already support 24MHz, like millis().

**Comment by MCUdude** [comment]
24 MHz support was added in 92536a7

**Comment by Jackjan4** [comment]
Cool! Now only updated corefiles and changed board.txt is missing. (?)
