### ISSUE TITLE
EXTERNAL_NUM_INTERRUPTS

### ISSUE THREAD

**Issue by xyybob** [MCUdude/MiniCore#82]
Compiler can't find EXTERNAL_NUM_INTERRUPTS, normally defined in wiring_private.h. I could just copy over that file from vanilla core files but is there something I need to be aware of with 328PB variant? According to the data sheet there are just the 2 external interrupts just like 328P - should wiring_private.h not be the same? Or I'm just doing it wrong...

**Comment by MCUdude** [comment]
I've moved EXTERNAL_NUM_INTERRUPTS to the [pins_arduino.h](https://github.com/MCUdude/MiniCore/blob/ed106a31f6565ab4000b93129eabfea37929d99f/avr/variants/pb-variant/pins_arduino.h#L33) file instead. IMO it makes much more sense to have all hardware related constants and definitions in one single file.

**Comment by xyybob** [comment]
Thanks.
