### ISSUE TITLE
Unrecognized atmega328pb

### ISSUE THREAD

**Issue by CRI73** [MCUdude/MiniCore#95]
hi my IDE report this error:
avr-g++: error: unrecognized argument in option '-mmcu=atmega328pb'

Arduino 1.8.9
Minicore V2.0.2
OSX 10.14.4

how I can fix it ?

Tanks 4 your help

**Comment by MCUdude** [comment]
Try updating your toolchain. Open the boards manager window and try to install the latest version of Arduino AVR boards (1.6.23 at the moment).

**Comment by CRI73** [comment]
hi
thanks for your answer
problem was HoodLoader2,
when I uninstall that boards, everything work fine

**Comment by MCUdude** [comment]
Great to hear you figured it out!
